site_name: Data Documentation
site_url: https://beatybiodiversitymuseum.github.io/data-documentation
nav:
  - Home:
      - index.md
  - Specify:
      - Tutorials:
          - specify/tutorials/getting-started.md
          - specify/tutorials/user-preferences.md
          - specify/tutorials/simple-search.md
          - specify/tutorials/queries.md
          - specify/tutorials/trees.md
          - specify/tutorials/workbench.md
      - How-to:
          - specify/how-to/keep-track-of-recently-entered-records.md
          - specify/how-to/edit-the-preptype-picklist.md
          - specify/how-to/download-a-query-as-a-csv.md

  - Portal:
      - portal/index.md
      - portal/searching.md
      - portal/navigating-to-a-particular-dataset.md
      - portal/downloading-data.md
      - portal/viewing-data.md
      - portal/ids.md
      - Programmatic Access:
          - portal/programmatic-access/gbif-api.md
  - Reference:
      - reference/index.md
      - reference/key-reference.md
      - reference/filter-terms.md

plugins:
  - glightbox
  - search
  - tags
  - material-plausible
theme:
  favicon: assets/favicon.ico
  logo: assets/beaty-logo-symbol-white.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      quote: fontawesome/solid/circle-question
    annotation: material/chevron-right-circle

  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - content.tabs.link
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.action.view
  font:
    text: Open Sans
  palette:
    - scheme: beaty
      primary: custom
      accent: red
repo_url: https://github.com/beatybiodiversitymuseum/data-documentation
repo_name: GitHub Repository
edit_uri: "edit/main/docs"
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - abbr
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css
copyright: <iframe src="https://status.beatymuseum.ubc.ca/badge" width="250" height="30" frameborder="0" scrolling="no"></iframe>
extra:
  analytics:
    provider: plausible
    domain: beatybiodiversitymuseum.github.io
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: fontawesome/regular/thumbs-up
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!
        - icon: fontawesome/regular/thumbs-down
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback!
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/BeatyMuseum
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/beatymuseum
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/beatymuseum
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/beatymuseum
